version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: translation_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: ${APP_KEY}
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: translation_service
      DB_USERNAME: root
      DB_PASSWORD: root
      CACHE_DRIVER: redis
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
    command: >
      sh -c "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:8.0
    container_name: translation_db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: translation_service
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: translation_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  swagger:
    image: swaggerapi/swagger-ui
    container_name: translation_swagger
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /api-docs/api-docs.json
    volumes:
      - ./storage/api-docs:/api-docs

volumes:
  mysql_data:
  redis_data:
